version: '3.0'

services:
  cpp:
    build: .
    volumes:
      - ~/.ssh:/home/vscode/.ssh
      - ~/.gitconfig:/home/vscode/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/home/vscode/cpp-examples
    working_dir: /home/vscode
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
    # gdb enabled
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
